# Generated by Django 2.1.7 on 2019-03-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentItem',
            new_name='JDCommentItem',
        ),
        migrations.AlterModelTable(
            name='jdaftercomment',
            table='jdaftercomment',
        ),
        migrations.AlterModelTable(
            name='jdcommentitem',
            table='jdcomment',
        ),
    ]
