# Generated by Django 2.1.7 on 2019-04-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='suningId',
            field=models.CharField(default=0, max_length=50, verbose_name='苏宁产品id'),
        ),
        migrations.AlterField(
            model_name='productname',
            name='jdProductId',
            field=models.CharField(default=0, max_length=50, verbose_name='京东产品id'),
        ),
    ]
