# Generated by Django 2.1.7 on 2019-03-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aftercomment',
            old_name='product_id',
            new_name='productid',
        ),
    ]
