# Generated by Django 2.1.7 on 2019-03-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='评论用户id'),
        ),
        migrations.AlterField(
            model_name='productsitem',
            name='_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='产品id'),
        ),
    ]
