# Generated by Django 2.1.7 on 2019-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_auto_20190318_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='referenceId',
            field=models.CharField(blank=True, max_length=100, verbose_name='产品总id'),
        ),
    ]
