# Generated by Django 2.1.7 on 2019-04-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_auto_20190403_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuNingComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=50, verbose_name='商品id')),
                ('content', models.TextField(verbose_name='评论')),
                ('nickName', models.CharField(max_length=50, verbose_name='买家名字')),
                ('levelName', models.CharField(max_length=10, verbose_name='买家等级')),
            ],
            options={
                'verbose_name': '苏宁商品评论',
                'verbose_name_plural': '苏宁商品评论',
                'db_table': 'suningcomment',
            },
        ),
        migrations.CreateModel(
            name='SuNingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=50, verbose_name='苏宁商品id')),
                ('producturl', models.CharField(max_length=50, verbose_name='购买地址')),
            ],
            options={
                'verbose_name': '苏宁商品',
                'verbose_name_plural': '苏宁商品',
                'db_table': 'suningproduct',
            },
        ),
        migrations.CreateModel(
            name='SuNingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=50, verbose_name='商品id')),
                ('labelName', models.CharField(max_length=50, verbose_name='名称')),
                ('labelCnt', models.IntegerField(verbose_name='数目')),
            ],
            options={
                'verbose_name': '苏宁商品标签',
                'verbose_name_plural': '苏宁商品标签',
                'db_table': 'suningtag',
            },
        ),
    ]
