# Generated by Django 2.1.7 on 2019-03-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_auto_20190331_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdhotcommenttagitem',
            name='type',
        ),
    ]
