# Generated by Django 2.1.7 on 2019-03-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0003_remove_jdhotcommenttagitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='creationTime',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='days',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='firstCategory',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='imageCount',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='productColor',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='productSize',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='referenceName',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='secondCategory',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='thirdCategory',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='userLevelId',
        ),
        migrations.RemoveField(
            model_name='jdcommentitem',
            name='userid',
        ),
    ]
