# Generated by Django 2.1.7 on 2019-03-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0003_auto_20190318_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentitem',
            name='imageCount',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='评论图片数量'),
        ),
    ]
