# Generated by Django 2.1.7 on 2019-04-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0003_suningcomment_suningproduct_suningtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suningproduct',
            name='producturl',
            field=models.URLField(verbose_name='购买地址'),
        ),
    ]
