# Generated by Django 2.1.7 on 2019-03-19 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0004_auto_20190318_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentid', models.CharField(max_length=100, verbose_name='评论人ID')),
                ('content', models.TextField(verbose_name='追评内容')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taobao.ProductsItem')),
            ],
            options={
                'verbose_name': '追评',
                'verbose_name_plural': '追评',
                'db_table': 'aftercomment',
            },
        ),
    ]
