# Generated by Django 2.1.7 on 2019-03-31 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0004_auto_20190331_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdcommentsummaryitem',
            name='generalRate',
        ),
        migrations.RemoveField(
            model_name='jdcommentsummaryitem',
            name='goodRate',
        ),
        migrations.RemoveField(
            model_name='jdcommentsummaryitem',
            name='poorRate',
        ),
    ]
