# Generated by Django 2.1.7 on 2019-03-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0005_aftercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftercomment',
            name='product_id',
            field=models.CharField(max_length=100, verbose_name='产品id'),
        ),
    ]
