# Generated by Django 2.1.7 on 2019-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0006_auto_20190319_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='产品id')),
                ('imgurl', models.CharField(max_length=150, verbose_name='产品封面')),
            ],
            options={
                'verbose_name': '产品链接',
                'verbose_name_plural': '产品链接',
                'db_table': 'productlink',
            },
        ),
    ]
