# Generated by Django 2.1.7 on 2019-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0007_productlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='imgurl',
            field=models.TextField(verbose_name='产品封面'),
        ),
    ]
